baseURL = 'https://andrewfranklinleo.com/'
languageCode = 'en-us'
title = 'Andrew Franklin Leo'
theme = 'sovereign-theme'
# Force Reload Trigger
enableEmoji = false
enableRobotsTXT = true

[build]
  writeStats = true

[minify]
  disableXML = true
  minifyOutput = true

[params]
  description = "The Sovereign Domain of Andrew Franklin Leo."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[cascade]]
  type = 'memory'
  [cascade._target]
    path = '/memory/**'
